### ISSUE TITLE
How to show the Notification in any screen with by calling this.popup.show() Method only once at particular screen

### ISSUE THREAD

**Issue by mahesh963** [carsonwah/react-native-push-notification-popup#16]
Hi, thanks for the awesome module. My requirement is, In my app i'm using chat functionality i need to show the notification type messages by calling this.popup.show() once in screen and need to get notification message in anywhere in the Application. Can you please suggest me how to fix it.

**Comment by carsonwah** [comment]
Hi. Sorry for the late reply. I would suggest you declare one more popup component in the individual screen where you need it, while keeping another one in a wrapper component just for any incoming notification.
