### ISSUE TITLE
BUG, On Android the pop up closes very fast after slide out

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [carsonwah/react-native-push-notification-popup#18]
BUG, On Android the pop up closes very fast after slide out

**Comment by ManigandanRaamanathan** [comment]
@carsonwah found that debug js mode will cause the pop up close fast.

**Comment by carsonwah** [comment]
Checked on Nexus 6 simulator debug JS mode. Cannot reproduce the issue. If you still experience this issue, please provide more environment details. Thanks.
