### ISSUE TITLE
Android not working.

### ISSUE THREAD

**Issue by peachlsy** [carsonwah/react-native-push-notification-popup#21]
Hi, thank you for your contribution of this library. It works perfect on iOS, but it seems like nothing happened in android emulator after this.pop.show()

Thank you!

**Comment by carsonwah** [comment]
Hi @peachlsy , could you provide more details for further investigation? Such as:

emulator: (android studio/geny motion)
device: (samsung, ...)
android version: 
react native version:
react-native-push-notification-popup version:
etc

**Comment by peachlsy** [comment]
Hi @carsonwah 
Thank you for your reply. Here are my environment:
emulator: android studio
device: pixel 3
android version: API 28, Android 9.0(Google APIs)
CPU: x86
react native version: 0.59.8
react-native-push-notification-popup version: ^1.3.0

Thanks!

**Comment by cohedz** [comment]
@carsonwah  you should use to show any where
    `    return (
      <Modal show={true} transparent>
        <Animated.View
          style={getAnimatedContainerStyle({ containerSlideOffsetY, containerDragOffsetY, containerScale })}
          {...this._panResponder.panHandlers}>
          <TouchableWithoutFeedback onPress={onPressAndSlideOut}>
            <View>
              {this.renderPopupContent()}
            </View>
          </TouchableWithoutFeedback>
        </Animated.View>
      </Modal>
    );`

**Comment by martin9908** [comment]
Hi Carson,
I'm also experiencing the same issue on my physical device. I'm using a 
Device: Xiaomi Redmi Note 3
react-native version: 0.33.0
react-native-push-notification-popup version: ^1.3.0

**Comment by sungsong88** [comment]
Hey guys. I had the same issue and I fixed my issue just by switching the order.

What I used to have based on `README.md`
```jsx
  ...
  render() {
    const { navigation } = this.props;

    return (
      <View style={{ flex: 1 }}>
        <NotificationPopup ref={popup => this.popup = popup} />
        <SwitchNavigator navigation={navigation} />
      </View>
    );
  }
}
```

What I have **now**:
```jsx
  ...
  render() {
    const { navigation } = this.props;

    return (
      <View style={{ flex: 1 }}>
        <SwitchNavigator navigation={navigation} />
        <NotificationPopup ref={popup => this.popup = popup} />
      </View>
    );
  }
}
```

Just by switching the order of my `Navigator` and the `NotificationPopup`, the popup is now showing for Android.

**Comment by carsonwah** [comment]
Hi guys, sorry for the late reply.

We are currently using `zIndex` to display the popup at the front of the scrren. It works well on iOS, but causes issues on Android.

Related discussions:
- [how to give z-index property in react native android app](https://stackoverflow.com/questions/39614040/how-to-give-z-index-property-in-react-native-android-app)
- [zIndex isn't working for a react native project](https://stackoverflow.com/questions/49121981/zindex-isnt-working-for-a-react-native-project)
- [React native: zIndex not taken seriously on Android](https://stackoverflow.com/questions/49078735/react-native-zindex-not-taken-seriously-on-android)
- [zIndex does not work with dynamic components on Android](https://github.com/facebook/react-native/issues/8968)

## Solution 1

Add `elevation` to [popupContainer](https://github.com/carsonwah/react-native-push-notification-popup/blob/9c3846d90dbe209bd86ce8b6b3bcbfe3b0defdf8/src/views/DefaultPopup.js#L281) component. But this may introduces some unwanted styles.

## Solution 2

From [Official Doc on zIndex](https://facebook.github.io/react-native/docs/layout-props#zindex):

> Normally, you don't use zIndex. Components render according to their order in the document tree, so later components draw over earlier ones.

So maybe we can remove the use of `zIndex` completely to work around this.

I will try that soon. Any comment or pull request is welcome.
