### ISSUE TITLE
Does DefaultPopup body support html?

### ISSUE THREAD

**Issue by ooo2003003v2** [carsonwah/react-native-push-notification-popup#27]
Hello there.
I'm having a problem with the default popup view. I was trying to push a html msg to my device but it doesn't support html in the body view. Will it becomes a feature in future?

**Comment by carsonwah** [comment]
DefaultPopup renders everything you pass into it. Your problem is due to React Native not rendering html string by default, if you just put it inside a `<View />`.

Please use a `<WebView />` to render the html string. You may refer to here: https://stackoverflow.com/a/29365213/6025730.
