### ISSUE TITLE
Undefined is not a function evaluation (popup.show...)

### ISSUE THREAD

**Issue by 16ntu1120** [carsonwah/react-native-push-notification-popup#43]
Whenever I try to show the notification for the first time this error is shown up and after pressing ctrl+s the and by sending the notification again from firebase the notification will appear perfectly. I'm using functional components with hooks.
let popup = useRef();

can anybody tell me the issue please? 
![issue](https://user-images.githubusercontent.com/61181128/131506696-d561a552-767f-4dbb-9267-b6403644c81a.JPG)

**Comment by nguyenanh15081998** [comment]
> Whenever I try to show the notification for the first time this error is shown up and after pressing ctrl+s the and by sending the notification again from firebase the notification will appear perfectly. I'm using functional components with hooks.
> let popup = useRef();
> 
> can anybody tell me the issue please?
> ![issue](https://user-images.githubusercontent.com/61181128/131506696-d561a552-767f-4dbb-9267-b6403644c81a.JPG)

Have you solved this problem yet?

**Comment by 16ntu1120** [comment]
@nguyenanh15081998 no I couldn't have you?

**Comment by 16ntu1120** [comment]
@nguyenanh15081998  yes I resolved this issue in my case I just made popup.show to popup.current.show it worked

**Comment by riddhi-0xblock** [comment]
yes I resolved this issue in my case I just made popup.show to popup.current.show it worked and declare ref like this
    const popup = useRef("popup");
